#!/usr/bin/env python
# encoding: utf-8

import argparse
from merge_requirements.manage_file import ManageFile, Merge

parser = argparse.ArgumentParser()

parser.add_argument(
    'first_file',
    help='first file to be merged'
)

parser.add_argument(
    'second_file',
    help='second file to be merged'
)

parser.add_argument(
    'more_files',
    nargs='*',
    help='list of more files to be merged'
)

args = parser.parse_args()

def main():

    mf = ManageFile(
        args.first_file,
        args.second_file,
        *args.more_files
    )

    mg = Merge(mf)
    mg.generate_requirements_txt()

if __name__ == '__main__':
    main()
